### ISSUE TITLE
[QUESTION] Add custom web page 

### ISSUE THREAD

**Issue by miskin1702** [wi-fi-analyzer/fluxion#19]
I'm new user on linux. Can i add custom web page to fluxion template? if answer is "yes" , how can i add ? anyone can help me?

**Comment by yusuf040** [comment]
Ewa miskin, just make your webpage and put in the sites folder. Then open fluxion.py with editor and basically you just copy and replace it. For example look for vodafone and every hit you copy the line or function and paste it and replace it whatever you want.

 echo -e "      "$red"["$yellow"$n"$red"]"$transparent" Vodafone    [ESP]";n=`expr $n + 1`
change Vodafone here and if you want language [ESP].

 elif [ "$webconf" = "32" ]; then
                                VODAFONE
break

change vodafone and change number [dont forget]

function VODAFONE {
        mkdir $DUMP_PATH/data &>$flux_output_device
        cp -r  $WORK_DIR/sites/vodafone_esp/* $DUMP_PATH/data
}

change function name(must be the same as previous step) and change path /sites/your webfolder/

that is it

**Comment by miskin1702** [comment]
Thank you yusuf.
