### ISSUE TITLE
Stuck at "Starting Captive Portal access point service..."

### ISSUE THREAD

**Issue by DevilslayerJtK** [wi-fi-analyzer/fluxion#21]
### Which version of fluxion are you using?
3(rev. 2)

### What distribution of Linux (including the version) are you running it on?
Kali Linux rolling

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
AWUS036ACH(Realtek RTL8812AU)

### Which is the driver for it?
RTL8812AU driver

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
1) I get the handshake via airodump-ng
2) I start fluxion as root via ./fluxion.sh
3) select language, interface and target device
4) Select "Captive Portal" [1]
5) select "Rogue AP - hostapd" [1]
6) Enter path to capture file
7) Verify via pyrit
8) Create new SSL certificate
9) Select language
10) Message "Starting Portal access point service..."

Nothing else happens. AFAIK new windows are supposed to open, but they don't. 
I also tried every language and verification via aircrack-ng and no change. I waited for >24 hours once, and it was still stuck.

Requirements are installed, setting up an AP manually via airbase-ng with DNS and DHCP works perfectly.

**Comment by DevilslayerJtK** [comment]
Setting up AP manually via hostapd works, too

**Comment by G30ATHGR** [comment]
I have tha same issue. How did you solved this?

**Comment by gusnips** [comment]
+1

**Comment by nazmusjj** [comment]
I also have the same issue..plz tell me how did you solved this problem...

**Comment by gusnips** [comment]
@nazmusjj  I changed my wifi card and it worked
