### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by deltaxflux** [wi-fi-analyzer/fluxion#3]
**Short expression:**
I shut down the original fluxion repo because of the law in Germany. It was **not** a spontaneous reaction more or less it was planned since February. The public  version will brick all other fluxion versions, because fluxion should not longer be public. 

**@everyone 
Please don't fork this project and share old files. It would be a pleasure for me.** 

Something about the new script: 
The only thing what the script does is: 

1. Delete Files

- Fluxion folder
- Tmp directory
- Handshake and pwlog folder
- Backups 

If you want to use it please use it private making this public again is against the License Agreement. Good luck !

**Comment by disquette38** [comment]
:( :(  It is a pity to stop the fluxion project, I am very sad, in any case thank you for this great project! **Thank you**.

**Comment by nisc3** [comment]
Do you have latest version of fluxion? @disquette

**Comment by Semenkk** [comment]
how to bay .. price?

**Comment by deltaxflux** [comment]
I don't want that fluxion is public, I will develop the tool and provide an onion site in couple of days

**Comment by disquette38** [comment]
@deltaxflux , Yes , of course !

**Comment by choy8433** [comment]
@deltaxflux thanks for the effort and keep going for this great project. cheer~

**Comment by minanagehsalalma** [comment]
@deltaxflux would you fix these two errors in the new version    1-  https://github.com/wi-fi-analyzer/fluxion/issues/2   2-  https://github.com/wi-fi-analyzer/fluxion/issues/1

**Comment by deltaxflux** [comment]
@minanagehsalalma
I'm not the developer

**Comment by minanagehsalalma** [comment]
@deltaxflux who is the developer ??

**Comment by alicans** [comment]
thx. waiting for onion site.

**Comment by deltaxflux** [comment]
Check the HF post

**Comment by minanagehsalalma** [comment]
what is HF  !!!!!

**Comment by teoxi** [comment]
Hi @deltaxflux and thanks for awesome tool! Did that mean that developing pentesting tools is illegal in Germany?..

**Comment by deltaxflux** [comment]
@teoxi kind of

**Comment by teoxi** [comment]
@deltaxflux, sorry for the off-topic, but would you please share more information about this restriction? I am planning moving to Germany and now you have confused me. Can I send you an email for more information?

**Comment by deltaxflux** [comment]
@teoxi  sure

**Comment by GabrielTK** [comment]
Can someone send me the HF post?? No HF in Brazil :(

**Comment by H600600x** [comment]
tell me what is HF post, i can send you. @GabrielTK

**Comment by GabrielTK** [comment]
HF = HackForums

On Apr 7, 2017 12:22 AM, "H600600x" <notifications@github.com<mailto:notifications@github.com>> wrote:

tell me what is HF post, i can send you. @GabrielTK<https://github.com/GabrielTK>

**Comment by H600600x** [comment]
ok i have no idea how to find it in hf @GabrielTK

**Comment by deltaxflux** [comment]
unlucky

**Comment by pierredias** [comment]
See the profile deltaflux ;)

**Comment by jaguarmoves** [comment]
no wonder the latest update destroy the file ... its fine i have the old version
