### ISSUE TITLE
White window "WIFI Monitor" 

### ISSUE THREAD

**Issue by armeclemes** [wi-fi-analyzer/fluxion#4]
### Which version of fluxion are you using?
Fluxion Version 2

### What distribution of Linux (including the version) are you running it on?
Raspbian : Linux raspberrypi 4.9.36-v7+ 

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
awus036ach, rtl8812au 

### Which is the driver for it?
rtl8812au

### Does it support injection ( output of aireplay-ng -9)
```
sudo aireplay-ng -9 wlan1
12:37:51  Trying broadcast probe requests...
12:37:52  No Answer...
12:37:52  Found 15 APs

12:37:52  Trying directed probe requests...
12:37:52  B0:B2:8F:78:**:** - channel: 1 - 'Livebox-****'
12:37:55  Ping (min/avg/max): 2.295ms/9.505ms/42.098ms Power: -53.50
12:37:55  16/30:  53%

12:37:55  Injection is working!
```

### General description of your issue along with the steps to reproduce it
When I lunch ./fluction.sh, all the softwares are in "OK!", I select 1 (language), I select 2 (My interface (wlan1)), I select "All channels" (1), 
And here, a white window open with nothing
![capture](https://user-images.githubusercontent.com/18120892/28268917-6947447a-6b00-11e7-9a42-cbeb4524156e.PNG)
And I can't do nothing.

**Comment by narciss1st** [comment]
Did you manage to resolve the issue? 
I have injected almost every rtl8812au.ko 4.9.0-kali4-amd64 module 
The awus036ach is amazing in terms of it's radius but I'm seriously doubting it's compatibility in monitor mode..
