### ISSUE TITLE
[2] Error: your wireless card  isn't supported   Do you want exit? [Yes / No]:        

### ISSUE THREAD

**Issue by JibinKoshy07** [wi-fi-analyzer/fluxion#42]
please help!

**Comment by ComBorgDev** [comment]
same for me

**Comment by ckzo** [comment]
idem

**Comment by doombot19400** [comment]
@JibinKoshy07 @ckzo  @ComBorgDev 
**`Try enabling monitor mode manually before starting fluxion`**, this worked for me I had the same issue.
**STEPS:**
`airmon-ng check kill
airmon-ng start wlan0`
Once you see monitor mode enabled, start fluxion normally.

**Comment by JibinKoshy07** [comment]
> @JibinKoshy07 @ckzo @ComBorgDev
> **Try enabling monitor mode manually before starting fluxion**, this worked for me I had the same issue.
> **STEPS:**
> `airmon-ng check kill`
> `airmon-ng start wlan0`
> Once you see monitor mode enabled, start fluxion normally.
